# Generated by Django 4.1 on 2023-02-10 08:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_name",
                    models.CharField(
                        help_text="僅允許英數字",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z]*$", "僅允許輸入英數字。"
                            )
                        ],
                        verbose_name="區塊名稱",
                    ),
                ),
                (
                    "block_dname",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="區塊顯示名稱"
                    ),
                ),
                (
                    "block_display_order",
                    models.IntegerField(help_text="不重複數字", verbose_name="區塊顯示順序"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_name",
                    models.CharField(
                        help_text="必填", max_length=30, verbose_name="資料名稱"
                    ),
                ),
                (
                    "data_dname",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="資料顯示名稱"
                    ),
                ),
                (
                    "data_ename",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="資料英文名稱"
                    ),
                ),
                (
                    "data_type1",
                    models.CharField(
                        help_text="必填", max_length=30, verbose_name="資料類別1"
                    ),
                ),
                (
                    "data_type2",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="資料類別2"
                    ),
                ),
                (
                    "data_dir",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="資料目錄"
                    ),
                ),
                (
                    "data_file",
                    models.CharField(
                        blank=True,
                        help_text="年：%Y、月：%m、日：%d、時：%H、分：%M、秒：%S",
                        max_length=100,
                        null=True,
                        verbose_name="資料檔案名稱",
                    ),
                ),
                (
                    "data_delay",
                    models.IntegerField(
                        blank=True, help_text="單位：分鐘", null=True, verbose_name="資料延遲"
                    ),
                ),
                (
                    "data_freq",
                    models.IntegerField(
                        blank=True, help_text="單位：分鐘", null=True, verbose_name="資料間隔"
                    ),
                ),
                (
                    "data_lst",
                    models.BooleanField(
                        blank=True, help_text="時區：臺北", null=True, verbose_name="是否為地區時"
                    ),
                ),
                (
                    "image_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="gallery.imageblock",
                        verbose_name="資料區塊",
                    ),
                ),
            ],
        ),
    ]
