# Generated by Django 4.1 on 2023-02-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="imageblock", name="block_display_order",),
    ]
