# Generated by Django 4.1 on 2023-02-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_remove_imageblock_block_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageblock",
            name="block_display_order",
            field=models.IntegerField(
                default=1, help_text="不重複數字", verbose_name="區塊顯示順序"
            ),
            preserve_default=False,
        ),
    ]
