# Generated by Django 4.1 on 2023-02-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_imageblock_display_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imageblock",
            old_name="display_order",
            new_name="block_display_order",
        ),
    ]
