# Generated by Django 4.1 on 2023-02-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0009_alter_imageblock_block_display_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemetadata",
            name="data_name",
            field=models.CharField(
                error_messages={"required": "請填入資料名稱。"},
                help_text="必填",
                max_length=30,
                verbose_name="資料名稱",
            ),
        ),
    ]
