# Generated by Django 4.1 on 2023-02-15 06:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0011_alter_imagemetadata_data_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        help_text="必填，僅允許英數字及'-'符號",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z\\-]*$", "僅允許輸入英數字及'-'符號。"
                            )
                        ],
                        verbose_name="種類名稱",
                    ),
                ),
                (
                    "type_dname",
                    models.CharField(
                        help_text="必填，僅允許英數字及'-'符號",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z\\-]*$", "僅允許輸入英數字及'-'符號。"
                            )
                        ],
                        verbose_name="種類顯示名稱",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="imageblock",
            name="block_display_order",
            field=models.IntegerField(
                help_text="必填，不重複數字", unique=True, verbose_name="區塊顯示順序"
            ),
        ),
        migrations.AlterField(
            model_name="imageblock",
            name="block_name",
            field=models.CharField(
                help_text="必填，僅允許英數字及'-'符號",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z\\-]*$", "僅允許輸入英數字及'-'符號。"
                    )
                ],
                verbose_name="區塊名稱",
            ),
        ),
        migrations.AlterField(
            model_name="imagemetadata",
            name="image_block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="gallery.imageblock",
                verbose_name="資料種類",
            ),
        ),
    ]
