# Generated by Django 4.1 on 2023-02-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0012_imagetype_alter_imageblock_block_display_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="imagemetadata", name="image_block",),
    ]
