# Generated by Django 4.1 on 2023-02-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0014_alter_imagetype_type_dname"),
    ]

    operations = [
        migrations.RenameModel(old_name="ImageType", new_name="ImageBlockType",),
    ]
