# Generated by Django 4.1 on 2023-02-15 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0015_rename_imagetype_imageblocktype"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemetadata",
            name="image_block_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="gallery.imageblocktype",
                verbose_name="資料區塊種類",
            ),
        ),
    ]
