# Generated by Django 4.1 on 2023-02-15 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0016_imagemetadata_image_block_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageblock",
            name="image_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="gallery.imagemetadata",
                verbose_name="圖片資訊",
            ),
        ),
    ]
