# Generated by Django 4.1 on 2023-02-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0017_imageblock_image_info"),
    ]

    operations = [
        migrations.RenameModel(old_name="ImageMetaData", new_name="ImageInfo",),
    ]
