# Generated by Django 4.1 on 2023-02-15 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0019_rename_imageblocktype_blocktype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocktype",
            name="type_name",
            field=models.CharField(
                help_text="必填，僅允許英數字及'-'符號",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z\\-]*$", "僅允許輸入英數字及'-'符號。"
                    )
                ],
                verbose_name="種類名稱",
            ),
        ),
        migrations.AlterField(
            model_name="imageblock",
            name="block_name",
            field=models.CharField(
                help_text="必填，僅允許英數字及'-'符號",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z\\-]*$", "僅允許輸入英數字及'-'符號。"
                    )
                ],
                verbose_name="區塊名稱",
            ),
        ),
        migrations.AlterField(
            model_name="imageinfo",
            name="data_name",
            field=models.CharField(
                help_text="必填", max_length=30, unique=True, verbose_name="資料名稱"
            ),
        ),
    ]
